// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourInfo.Infrastracture.Repository.EFCore;

namespace TourInfo.Infrastracture.Migrations
{
    [DbContext(typeof(TourInfoDbContext))]
    [Migration("20200423025749_imageurl_speciallocalproduct")]
    partial class imageurl_speciallocalproduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TourInfo.Domain.DomainModel.Rapi.Projectinfo", b =>
                {
                    b.Property<int>("pid");

                    b.Property<string>("Fingerprint");

                    b.Property<string>("Version");

                    b.Property<string>("appid");

                    b.Property<string>("areacode");

                    b.Property<DateTime>("crtdate");

                    b.Property<string>("defaultlogo");

                    b.Property<bool>("deleteflag");

                    b.Property<string>("desc");

                    b.Property<string>("detailfoot");

                    b.Property<string>("detailhead");

                    b.Property<string>("homeurl");

                    b.Property<int>("id");

                    b.Property<bool>("iscomment");

                    b.Property<string>("pname");

                    b.Property<int>("subpid");

                    b.Property<string>("topjumpurl");

                    b.Property<string>("toppicurl");

                    b.Property<string>("topresourceurl");

                    b.Property<string>("topvideourl");

                    b.Property<DateTime>("updatetime");

                    b.Property<string>("wapbgimg");

                    b.HasKey("pid");

                    b.ToTable("Projectinfo");
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.Rapi.Pubinfounit", b =>
                {
                    b.Property<int>("unitid");

                    b.Property<string>("Fingerprint");

                    b.Property<string>("Version");

                    b.Property<string>("address");

                    b.Property<string>("areacode");

                    b.Property<string>("areaname");

                    b.Property<int>("bedcount");

                    b.Property<string>("booktel");

                    b.Property<int>("boxcount");

                    b.Property<string>("businesslicense");

                    b.Property<string>("businesstime");

                    b.Property<int>("commentnum");

                    b.Property<string>("complainttel");

                    b.Property<DateTime>("crtdate");

                    b.Property<string>("decorationtime");

                    b.Property<bool>("deleteflag");

                    b.Property<string>("desc");

                    b.Property<string>("detailurl");

                    b.Property<string>("environmentrating");

                    b.Property<string>("facilityrating");

                    b.Property<string>("favouredpolicy");

                    b.Property<string>("fax");

                    b.Property<string>("hygienerating");

                    b.Property<int>("id");

                    b.Property<int>("id5a");

                    b.Property<int>("imgnum");

                    b.Property<string>("infotel");

                    b.Property<string>("innertrafic");

                    b.Property<int>("level");

                    b.Property<string>("licenseno");

                    b.Property<string>("logopic");

                    b.Property<string>("mainline");

                    b.Property<string>("manager");

                    b.Property<string>("managertel");

                    b.Property<int>("maxcapacity");

                    b.Property<string>("memo");

                    b.Property<string>("name5a");

                    b.Property<string>("opentime");

                    b.Property<float>("orderno");

                    b.Property<string>("overallrating");

                    b.Property<float>("personprice");

                    b.Property<int>("pid");

                    b.Property<string>("poitypename");

                    b.Property<string>("poitypetag");

                    b.Property<string>("postcode");

                    b.Property<string>("pricedesc");

                    b.Property<string>("publictrafic");

                    b.Property<string>("reservefield1");

                    b.Property<string>("reservefield2");

                    b.Property<string>("reservefield3");

                    b.Property<string>("reservefield4");

                    b.Property<string>("reservefield5");

                    b.Property<string>("reservefield6");

                    b.Property<string>("reservefield7");

                    b.Property<string>("reservefield8");

                    b.Property<string>("reservefield9");

                    b.Property<int>("roomcount");

                    b.Property<float>("roomprice");

                    b.Property<int>("seatcount");

                    b.Property<string>("servicerating");

                    b.Property<string>("shortname");

                    b.Property<int>("sourcefrom");

                    b.Property<int>("state");

                    b.Property<string>("telephone");

                    b.Property<float>("ticketprice");

                    b.Property<string>("tips");

                    b.Property<int>("typeid");

                    b.Property<string>("unitname");

                    b.Property<DateTime>("updatetime");

                    b.Property<string>("url");

                    b.Property<string>("url360");

                    b.Property<string>("zonecode");

                    b.HasKey("unitid");

                    b.ToTable("Pubinfounit");
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.Rapi.Pubinfounitchild", b =>
                {
                    b.Property<int>("childid");

                    b.Property<string>("Fingerprint");

                    b.Property<string>("Version");

                    b.Property<string>("childname");

                    b.Property<DateTime>("crtdate");

                    b.Property<bool>("deleteflag");

                    b.Property<string>("desc");

                    b.Property<string>("guidetext");

                    b.Property<string>("guidevoice");

                    b.Property<int>("id");

                    b.Property<bool>("isshow");

                    b.Property<string>("memo");

                    b.Property<float>("orderno");

                    b.Property<int>("pid");

                    b.Property<string>("price");

                    b.Property<int>("unitid");

                    b.Property<DateTime>("updatetime");

                    b.HasKey("childid");

                    b.HasIndex("childid");

                    b.ToTable("Pubinfounitchild");
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.Rapi.Pubmediainfo", b =>
                {
                    b.Property<int>("mediaid");

                    b.Property<string>("Fingerprint");

                    b.Property<string>("Version");

                    b.Property<DateTime>("crtdate");

                    b.Property<bool>("deleteflag");

                    b.Property<string>("desc");

                    b.Property<int>("id");

                    b.Property<bool>("isshow");

                    b.Property<string>("medianame");

                    b.Property<int>("mediatypeid");

                    b.Property<string>("memo");

                    b.Property<float>("orderno");

                    b.Property<int>("pid");

                    b.Property<bool>("topshow");

                    b.Property<int>("typepicid");

                    b.Property<int>("unitid");

                    b.Property<DateTime>("updatetime");

                    b.Property<string>("videourl");

                    b.HasKey("mediaid");

                    b.ToTable("Pubmediainfo");
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.Rapi.Pubunittag", b =>
                {
                    b.Property<int>("unittagid");

                    b.Property<string>("Fingerprint");

                    b.Property<string>("Version");

                    b.Property<int>("id");

                    b.Property<int>("pid");

                    b.Property<int>("tagid");

                    b.Property<string>("tagvalue");

                    b.Property<int>("unitid");

                    b.HasKey("unittagid");

                    b.ToTable("Pubunittag");
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.Rapi.Typefield", b =>
                {
                    b.Property<int>("id");

                    b.Property<string>("Fingerprint");

                    b.Property<string>("Version");

                    b.Property<DateTime>("crtdate");

                    b.Property<string>("customname");

                    b.Property<bool>("deleteflag");

                    b.Property<int>("displayorder");

                    b.Property<string>("fieldname");

                    b.Property<string>("fieldtype");

                    b.Property<string>("groupname");

                    b.Property<bool>("isdisplay");

                    b.Property<bool>("isedit");

                    b.Property<float>("orderno");

                    b.Property<int>("pid");

                    b.Property<int>("typeid");

                    b.Property<DateTime>("updatetime");

                    b.HasKey("id");

                    b.ToTable("Typefield");
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.Rapi.Typeinfo", b =>
                {
                    b.Property<int>("typeid");

                    b.Property<string>("Fingerprint");

                    b.Property<string>("Version");

                    b.Property<DateTime>("crtdate");

                    b.Property<bool>("deleteflag");

                    b.Property<string>("editurl");

                    b.Property<bool>("existschild");

                    b.Property<bool>("existsroom");

                    b.Property<bool>("existsscenic");

                    b.Property<int>("id");

                    b.Property<bool>("isshow");

                    b.Property<string>("mobilememo");

                    b.Property<float>("orderno");

                    b.Property<int>("pid");

                    b.Property<int>("ptypeid");

                    b.Property<string>("showurl");

                    b.Property<string>("typename");

                    b.Property<DateTime>("updatetime");

                    b.HasKey("typeid");

                    b.ToTable("Typeinfo");
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.Rapi.Typepic", b =>
                {
                    b.Property<int>("id");

                    b.Property<string>("Fingerprint");

                    b.Property<string>("Version");

                    b.Property<DateTime>("crtdate");

                    b.Property<bool>("deleteflag");

                    b.Property<string>("groupname");

                    b.Property<int>("mediatypeid");

                    b.Property<string>("mediatypename");

                    b.Property<float>("orderno");

                    b.Property<int>("pid");

                    b.Property<int>("typeid");

                    b.Property<DateTime>("updatetime");

                    b.HasKey("id");

                    b.ToTable("Typepic");
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.Rapi.Typetag", b =>
                {
                    b.Property<int>("id");

                    b.Property<string>("Fingerprint");

                    b.Property<string>("Version");

                    b.Property<DateTime>("crtdate");

                    b.Property<bool>("deleteflag");

                    b.Property<string>("groupname");

                    b.Property<float>("orderno");

                    b.Property<int>("pid");

                    b.Property<string>("tagname");

                    b.Property<int>("typeid");

                    b.Property<DateTime>("updatetime");

                    b.HasKey("id");

                    b.ToTable("Typetag");
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.SDTA.CityGuideDetail+Data", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("author");

                    b.Property<string>("cms_user_id");

                    b.Property<int>("collectscount");

                    b.Property<int>("commentcount");

                    b.Property<string>("commentscore");

                    b.Property<string>("content");

                    b.Property<string>("created_at");

                    b.Property<string>("description");

                    b.Property<int>("detailid");

                    b.Property<int>("featured");

                    b.Property<int>("likescount");

                    b.Property<string>("name");

                    b.Property<int>("primary_category");

                    b.Property<int>("rank");

                    b.Property<int>("status");

                    b.Property<string>("updated_at");

                    b.Property<int>("user_id");

                    b.Property<int>("views");

                    b.HasKey("id");

                    b.ToTable("SDTACityGuideDetail");
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.SDTA.FoodDetail+Data", b =>
                {
                    b.Property<int>("id");

                    b.Property<string>("areaname");

                    b.Property<string>("cityname");

                    b.Property<int>("collectscount");

                    b.Property<int>("commentcount");

                    b.Property<string>("commentscore");

                    b.Property<string>("compresspic");

                    b.Property<string>("created_at");

                    b.Property<string>("destination_id");

                    b.Property<string>("food_enname");

                    b.Property<string>("food_fullnane");

                    b.Property<string>("food_price");

                    b.Property<string>("food_recmmond");

                    b.Property<string>("food_shortname");

                    b.Property<string>("food_type_id");

                    b.Property<int>("is_404");

                    b.Property<string>("keywords");

                    b.Property<int>("likescount");

                    b.Property<string>("perlink");

                    b.Property<int>("rank");

                    b.Property<string>("res_type_rela");

                    b.Property<string>("restaurant_id");

                    b.Property<string>("snack_int");

                    b.Property<string>("snack_intr_m");

                    b.Property<string>("snack_name");

                    b.Property<string>("snack_pho");

                    b.Property<int>("source");

                    b.Property<int>("state");

                    b.Property<string>("tags");

                    b.Property<string>("unitcode");

                    b.Property<string>("updated_at");

                    b.Property<string>("user_id");

                    b.HasKey("id");

                    b.ToTable("SDTAFoodDetail");
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.SDTA.LineDetail", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fingerprint");

                    b.Property<string>("Version");

                    b.Property<string>("bestSeason");

                    b.Property<string>("city");

                    b.Property<string>("name");

                    b.Property<string>("tags");

                    b.HasKey("id");

                    b.ToTable("SDTALineDetail");
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.SDTA.LineDetailScenic+Doc+Source", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fingerprint");

                    b.Property<string>("Version");

                    b.Property<string>("address");

                    b.Property<string>("area");

                    b.Property<string>("buyable");

                    b.Property<int>("city");

                    b.Property<int>("city_order");

                    b.Property<string>("contact");

                    b.Property<int>("date_for_order");

                    b.Property<string>("description");

                    b.Property<string>("ele_id");

                    b.Property<string>("ele_type");

                    b.Property<string>("ele_type_name");

                    b.Property<string>("ele_type_name_en");

                    b.Property<int>("level");

                    b.Property<string>("level_name");

                    b.Property<string>("location");

                    b.Property<double>("lowest_price");

                    b.Property<string>("lvl1");

                    b.Property<string>("name_cn");

                    b.Property<int>("rank");

                    b.HasKey("id");

                    b.ToTable("SDTALineDetailScenicDocSource");
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.SDTA.SpecialLocalProductDetail+Data", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("areaname");

                    b.Property<string>("auditdate");

                    b.Property<string>("cityname");

                    b.Property<int>("collectscount");

                    b.Property<string>("comm_type_id");

                    b.Property<string>("comm_type_name");

                    b.Property<int>("commentcount");

                    b.Property<string>("commentscore");

                    b.Property<string>("commodity_id");

                    b.Property<string>("commodity_intr");

                    b.Property<int?>("commodity_typeid");

                    b.Property<string>("compresspic");

                    b.Property<string>("created_at");

                    b.Property<string>("destination_id");

                    b.Property<string>("full_name");

                    b.Property<int>("is_404");

                    b.Property<string>("keywords");

                    b.Property<int>("likescount");

                    b.Property<string>("manufacturer_inf");

                    b.Property<string>("name_cn");

                    b.Property<string>("perlink");

                    b.Property<string>("price_desc");

                    b.Property<int>("rank");

                    b.Property<string>("short_name");

                    b.Property<int>("state");

                    b.Property<string>("tags");

                    b.Property<string>("updated_at");

                    b.Property<string>("version");

                    b.HasKey("id");

                    b.HasIndex("commodity_typeid");

                    b.ToTable("SDTASpecialLocalProductDetail");
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.SDTA.SpecialLocalProductDetail+Data+CommodityType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("comm_name");

                    b.Property<string>("comm_type_id");

                    b.Property<string>("comm_type_id_p");

                    b.Property<string>("created_at");

                    b.Property<string>("deleted_at");

                    b.Property<int>("grade");

                    b.Property<string>("updated_at");

                    b.Property<string>("user_id");

                    b.HasKey("id");

                    b.ToTable("CommodityType");
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.Video.Video", b =>
                {
                    b.Property<int>("id");

                    b.Property<string>("Fingerprint");

                    b.Property<string>("Version");

                    b.Property<string>("attachment");

                    b.Property<string>("author");

                    b.Property<string>("checkname");

                    b.Property<int>("checkstate");

                    b.Property<DateTime?>("checktime");

                    b.Property<string>("checkuser");

                    b.Property<DateTime>("createtime");

                    b.Property<bool>("deleteflag");

                    b.Property<string>("editname");

                    b.Property<string>("edituser");

                    b.Property<string>("img");

                    b.Property<bool>("iscycle");

                    b.Property<bool>("istop");

                    b.Property<string>("jumpurl");

                    b.Property<int>("mid");

                    b.Property<int>("orderno");

                    b.Property<int>("pid");

                    b.Property<DateTime>("pubtime");

                    b.Property<string>("subtitle");

                    b.Property<string>("summary");

                    b.Property<string>("title");

                    b.Property<DateTime>("updatetime");

                    b.HasKey("id");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.WHY.WhyModel", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fingerprint");

                    b.Property<int>("RapiId");

                    b.Property<string>("Version");

                    b.Property<string>("addressInfo");

                    b.Property<string>("contact");

                    b.Property<string>("name");

                    b.Property<string>("summary");

                    b.Property<string>("website");

                    b.HasKey("id");

                    b.ToTable("WHYDetailOrganizations");
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.ZiBoWechatNews.ZiBoWechatNews", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fingerprint");

                    b.Property<string>("Version");

                    b.Property<string>("img");

                    b.Property<DateTime>("pubtime");

                    b.Property<string>("title");

                    b.Property<string>("url");

                    b.HasKey("id");

                    b.ToTable("ZiBoWechatNews");
                });

            modelBuilder.Entity("TourInfo.Domain.EWQYPlaceTypeEntity", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Fingerprint");

                    b.Property<int>("PlaceType");

                    b.Property<string>("Version");

                    b.HasKey("id");

                    b.ToTable("EWQYPlaceTypeEntities");

                    b.HasDiscriminator<string>("Discriminator").HasValue("EWQYPlaceTypeEntity");
                });

            modelBuilder.Entity("TourInfo.Domain.ZBTA.ZbtaNews", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fingerprint");

                    b.Property<string>("Version");

                    b.Property<string>("back1");

                    b.Property<string>("checkState");

                    b.Property<string>("createUser");

                    b.Property<string>("created");

                    b.Property<string>("releaseTime");

                    b.Property<string>("titles");

                    b.HasKey("id");

                    b.ToTable("ZbtaNews");
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.EWQY.CompanyVenueType", b =>
                {
                    b.HasBaseType("TourInfo.Domain.EWQYPlaceTypeEntity");

                    b.Property<string>("name")
                        .HasColumnName("CompanyVenueType_name");

                    b.HasDiscriminator().HasValue("CompanyVenueType");
                });

            modelBuilder.Entity("TourInfo.Domain.EWQYEntity", b =>
                {
                    b.HasBaseType("TourInfo.Domain.EWQYPlaceTypeEntity");

                    b.HasDiscriminator().HasValue("EWQYEntity");
                });

            modelBuilder.Entity("TourInfo.Domain.Activity", b =>
                {
                    b.HasBaseType("TourInfo.Domain.EWQYEntity");

                    b.Property<string>("address");

                    b.Property<string>("createTime");

                    b.Property<int>("credits");

                    b.Property<string>("detail");

                    b.Property<string>("endTime");

                    b.Property<bool>("isShared");

                    b.Property<string>("name");

                    b.Property<string>("startTime");

                    b.HasDiscriminator().HasValue("Activity");
                });

            modelBuilder.Entity("TourInfo.Domain.CompanyVenue", b =>
                {
                    b.HasBaseType("TourInfo.Domain.EWQYEntity");

                    b.Property<string>("address")
                        .HasColumnName("CompanyVenue_address");

                    b.Property<string>("introduction");

                    b.Property<string>("isFavorite");

                    b.Property<string>("name")
                        .HasColumnName("CompanyVenue_name");

                    b.Property<string>("satisfactionScore");

                    b.Property<string>("serviceNote");

                    b.Property<string>("serviceTimeEnd");

                    b.Property<string>("serviceTimeStart");

                    b.Property<string>("telNumber");

                    b.Property<string>("typeId");

                    b.HasDiscriminator().HasValue("CompanyVenue");
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.Rapi.Pubinfounit", b =>
                {
                    b.OwnsOne("TourInfo.Domain.Base.ImageUrl", "flagpic", b1 =>
                        {
                            b1.Property<int?>("Pubinfounitid");

                            b1.Property<string>("LocalizedUrl");

                            b1.Property<string>("OriginalUrl");

                            b1.HasKey("Pubinfounitid");

                            b1.ToTable("Pubinfounit");

                            b1.HasOne("TourInfo.Domain.DomainModel.Rapi.Pubinfounit")
                                .WithOne("flagpic")
                                .HasForeignKey("TourInfo.Domain.Base.ImageUrl", "Pubinfounitid")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TourInfo.Domain.Base.Location", "gps", b1 =>
                        {
                            b1.Property<int?>("Pubinfounitid");

                            b1.Property<double>("Latitude");

                            b1.Property<double>("Longitude");

                            b1.HasKey("Pubinfounitid");

                            b1.ToTable("Pubinfounit");

                            b1.HasOne("TourInfo.Domain.DomainModel.Rapi.Pubinfounit")
                                .WithOne("gps")
                                .HasForeignKey("TourInfo.Domain.Base.Location", "Pubinfounitid")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TourInfo.Domain.Base.Location", "gpsbd", b1 =>
                        {
                            b1.Property<int?>("Pubinfounitid");

                            b1.Property<double>("Latitude");

                            b1.Property<double>("Longitude");

                            b1.HasKey("Pubinfounitid");

                            b1.ToTable("Pubinfounit");

                            b1.HasOne("TourInfo.Domain.DomainModel.Rapi.Pubinfounit")
                                .WithOne("gpsbd")
                                .HasForeignKey("TourInfo.Domain.Base.Location", "Pubinfounitid")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TourInfo.Domain.Base.Location", "gpsgd", b1 =>
                        {
                            b1.Property<int?>("Pubinfounitid");

                            b1.Property<double>("Latitude");

                            b1.Property<double>("Longitude");

                            b1.HasKey("Pubinfounitid");

                            b1.ToTable("Pubinfounit");

                            b1.HasOne("TourInfo.Domain.DomainModel.Rapi.Pubinfounit")
                                .WithOne("gpsgd")
                                .HasForeignKey("TourInfo.Domain.Base.Location", "Pubinfounitid")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.Rapi.Pubinfounitchild", b =>
                {
                    b.OwnsOne("TourInfo.Domain.Base.ImageUrl", "flagurl", b1 =>
                        {
                            b1.Property<int>("Pubinfounitchildchildid");

                            b1.Property<string>("LocalizedUrl");

                            b1.Property<string>("OriginalUrl");

                            b1.HasKey("Pubinfounitchildchildid");

                            b1.ToTable("Pubinfounitchild");

                            b1.HasOne("TourInfo.Domain.DomainModel.Rapi.Pubinfounitchild")
                                .WithOne("flagurl")
                                .HasForeignKey("TourInfo.Domain.Base.ImageUrl", "Pubinfounitchildchildid")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TourInfo.Domain.Base.Location", "gps", b1 =>
                        {
                            b1.Property<int>("Pubinfounitchildchildid");

                            b1.Property<double>("Latitude");

                            b1.Property<double>("Longitude");

                            b1.HasKey("Pubinfounitchildchildid");

                            b1.ToTable("Pubinfounitchild");

                            b1.HasOne("TourInfo.Domain.DomainModel.Rapi.Pubinfounitchild")
                                .WithOne("gps")
                                .HasForeignKey("TourInfo.Domain.Base.Location", "Pubinfounitchildchildid")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TourInfo.Domain.Base.Location", "gpsbd", b1 =>
                        {
                            b1.Property<int>("Pubinfounitchildchildid");

                            b1.Property<double>("Latitude");

                            b1.Property<double>("Longitude");

                            b1.HasKey("Pubinfounitchildchildid");

                            b1.ToTable("Pubinfounitchild");

                            b1.HasOne("TourInfo.Domain.DomainModel.Rapi.Pubinfounitchild")
                                .WithOne("gpsbd")
                                .HasForeignKey("TourInfo.Domain.Base.Location", "Pubinfounitchildchildid")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TourInfo.Domain.Base.Location", "gpsgd", b1 =>
                        {
                            b1.Property<int>("Pubinfounitchildchildid");

                            b1.Property<double>("Latitude");

                            b1.Property<double>("Longitude");

                            b1.HasKey("Pubinfounitchildchildid");

                            b1.ToTable("Pubinfounitchild");

                            b1.HasOne("TourInfo.Domain.DomainModel.Rapi.Pubinfounitchild")
                                .WithOne("gpsgd")
                                .HasForeignKey("TourInfo.Domain.Base.Location", "Pubinfounitchildchildid")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.Rapi.Pubmediainfo", b =>
                {
                    b.OwnsOne("TourInfo.Domain.Base.ImageUrl", "mediaurl", b1 =>
                        {
                            b1.Property<int?>("Pubmediainfoid");

                            b1.Property<string>("LocalizedUrl");

                            b1.Property<string>("OriginalUrl");

                            b1.HasKey("Pubmediainfoid");

                            b1.ToTable("Pubmediainfo");

                            b1.HasOne("TourInfo.Domain.DomainModel.Rapi.Pubmediainfo")
                                .WithOne("mediaurl")
                                .HasForeignKey("TourInfo.Domain.Base.ImageUrl", "Pubmediainfoid")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.Rapi.Typeinfo", b =>
                {
                    b.OwnsOne("TourInfo.Domain.Base.ImageUrl", "wapshowimg", b1 =>
                        {
                            b1.Property<int?>("Typeinfoid");

                            b1.Property<string>("LocalizedUrl");

                            b1.Property<string>("OriginalUrl");

                            b1.HasKey("Typeinfoid");

                            b1.ToTable("Typeinfo");

                            b1.HasOne("TourInfo.Domain.DomainModel.Rapi.Typeinfo")
                                .WithOne("wapshowimg")
                                .HasForeignKey("TourInfo.Domain.Base.ImageUrl", "Typeinfoid")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.SDTA.CityGuideDetail+Data", b =>
                {
                    b.OwnsOne("TourInfo.Domain.DomainModel.SDTA.CityGuideDetail+Data+Category", "category", b1 =>
                        {
                            b1.Property<string>("Dataid");

                            b1.Property<string>("created_at");

                            b1.Property<string>("description");

                            b1.Property<int>("featured");

                            b1.Property<string>("icon");

                            b1.Property<int>("id");

                            b1.Property<int>("is_default");

                            b1.Property<string>("name");

                            b1.Property<int>("order");

                            b1.Property<int>("parent_id");

                            b1.Property<string>("slug");

                            b1.Property<int>("status");

                            b1.Property<string>("updated_at");

                            b1.Property<int>("user_id");

                            b1.HasKey("Dataid");

                            b1.ToTable("SDTACityGuideDetailCategory");

                            b1.HasOne("TourInfo.Domain.DomainModel.SDTA.CityGuideDetail+Data")
                                .WithOne("category")
                                .HasForeignKey("TourInfo.Domain.DomainModel.SDTA.CityGuideDetail+Data+Category", "Dataid")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TourInfo.Domain.DomainModel.SDTA.CityGuideDetail+Data+Pics", "pics", b1 =>
                        {
                            b1.Property<string>("Dataid");

                            b1.Property<int>("content_id");

                            b1.Property<string>("created_at");

                            b1.Property<string>("deleted_at");

                            b1.Property<int>("id");

                            b1.Property<string>("reference");

                            b1.Property<string>("updated_at");

                            b1.HasKey("Dataid");

                            b1.ToTable("SDTACityGuideDetailPics");

                            b1.HasOne("TourInfo.Domain.DomainModel.SDTA.CityGuideDetail+Data")
                                .WithOne("pics")
                                .HasForeignKey("TourInfo.Domain.DomainModel.SDTA.CityGuideDetail+Data+Pics", "Dataid")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsMany("TourInfo.Domain.DomainModel.SDTA.CityGuideDetail+Data+Pics+Image", "images", b2 =>
                                {
                                    b2.Property<string>("GuideId");

                                    b2.Property<string>("description");

                                    b2.HasKey("GuideId", "description");

                                    b2.ToTable("SDTACityGuideDetailPicImage");

                                    b2.HasOne("TourInfo.Domain.DomainModel.SDTA.CityGuideDetail+Data+Pics")
                                        .WithMany("images")
                                        .HasForeignKey("GuideId")
                                        .OnDelete(DeleteBehavior.Cascade);

                                    b2.OwnsOne("TourInfo.Domain.Base.ImageUrl", "img", b3 =>
                                        {
                                            b3.Property<string>("ImageGuideId");

                                            b3.Property<string>("Imagedescription");

                                            b3.Property<string>("LocalizedUrl");

                                            b3.Property<string>("OriginalUrl");

                                            b3.HasKey("ImageGuideId", "Imagedescription");

                                            b3.ToTable("SDTACityGuideDetailPicImage");

                                            b3.HasOne("TourInfo.Domain.DomainModel.SDTA.CityGuideDetail+Data+Pics+Image")
                                                .WithOne("img")
                                                .HasForeignKey("TourInfo.Domain.Base.ImageUrl", "ImageGuideId", "Imagedescription")
                                                .OnDelete(DeleteBehavior.Cascade);
                                        });
                                });
                        });

                    b.OwnsOne("TourInfo.Domain.Base.ImageUrl", "image", b1 =>
                        {
                            b1.Property<string>("Dataid");

                            b1.Property<string>("LocalizedUrl");

                            b1.Property<string>("OriginalUrl");

                            b1.HasKey("Dataid");

                            b1.ToTable("SDTACityGuideDetail");

                            b1.HasOne("TourInfo.Domain.DomainModel.SDTA.CityGuideDetail+Data")
                                .WithOne("image")
                                .HasForeignKey("TourInfo.Domain.Base.ImageUrl", "Dataid")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.SDTA.FoodDetail+Data", b =>
                {
                    b.OwnsOne("TourInfo.Domain.DomainModel.SDTA.FoodDetail+Data+Destination", "destination", b1 =>
                        {
                            b1.Property<int>("FoodId");

                            b1.Property<int>("id");

                            b1.Property<string>("adm_address");

                            b1.Property<string>("adm_name");

                            b1.Property<string>("adm_phone");

                            b1.Property<string>("airlines");

                            b1.Property<string>("area_id");

                            b1.Property<int>("audit_state");

                            b1.Property<string>("bus");

                            b1.Property<string>("charmcitypic");

                            b1.Property<string>("cityname");

                            b1.Property<string>("clim_des");

                            b1.Property<string>("created_at");

                            b1.Property<string>("culture");

                            b1.Property<string>("daren_picture");

                            b1.Property<string>("dest_adver");

                            b1.Property<string>("dest_des");

                            b1.Property<int>("dest_type_id");

                            b1.Property<string>("destination_id");

                            b1.Property<string>("destname");

                            b1.Property<string>("fea_inf");

                            b1.Property<string>("fea_traffic");

                            b1.Property<string>("full_name");

                            b1.Property<string>("highway");

                            b1.Property<int>("is_404");

                            b1.Property<string>("keywords");

                            b1.Property<string>("latitude");

                            b1.Property<string>("longitude");

                            b1.Property<string>("notes_des");

                            b1.Property<string>("railway");

                            b1.Property<int>("rank");

                            b1.Property<string>("short_name");

                            b1.Property<string>("tags");

                            b1.Property<string>("taxi");

                            b1.Property<string>("tou_taboo");

                            b1.Property<string>("updated_at");

                            b1.Property<string>("water_carriage");

                            b1.Property<string>("website");

                            b1.HasKey("FoodId", "id");

                            b1.HasIndex("FoodId")
                                .IsUnique();

                            b1.ToTable("SDTAFoodDetailDestination");

                            b1.HasOne("TourInfo.Domain.DomainModel.SDTA.FoodDetail+Data")
                                .WithOne("destination")
                                .HasForeignKey("TourInfo.Domain.DomainModel.SDTA.FoodDetail+Data+Destination", "FoodId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsOne("TourInfo.Domain.Base.ImageUrl", "defaultphoto", b2 =>
                                {
                                    b2.Property<int>("DestinationFoodId");

                                    b2.Property<int>("Destinationid");

                                    b2.Property<string>("LocalizedUrl");

                                    b2.Property<string>("OriginalUrl");

                                    b2.HasKey("DestinationFoodId", "Destinationid");

                                    b2.ToTable("SDTAFoodDetailDestination");

                                    b2.HasOne("TourInfo.Domain.DomainModel.SDTA.FoodDetail+Data+Destination")
                                        .WithOne("defaultphoto")
                                        .HasForeignKey("TourInfo.Domain.Base.ImageUrl", "DestinationFoodId", "Destinationid")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });
                        });

                    b.OwnsMany("TourInfo.Domain.DomainModel.SDTA.FoodDetail+Data+FilterPicture", "filter_pictures", b1 =>
                        {
                            b1.Property<int>("FoodId");

                            b1.Property<int>("id");

                            b1.Property<string>("created_at");

                            b1.Property<string>("deleted_at");

                            b1.Property<int>("is_404");

                            b1.Property<string>("pho_format");

                            b1.Property<string>("pho_id");

                            b1.Property<string>("pho_name");

                            b1.Property<string>("pho_type");

                            b1.Property<string>("picable_id");

                            b1.Property<string>("picable_type");

                            b1.Property<int>("rank");

                            b1.Property<string>("updated_at");

                            b1.HasKey("FoodId", "id");

                            b1.ToTable("SDTAFoodDetailFilterPictures");

                            b1.HasOne("TourInfo.Domain.DomainModel.SDTA.FoodDetail+Data")
                                .WithMany("filter_pictures")
                                .HasForeignKey("FoodId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsOne("TourInfo.Domain.Base.ImageUrl", "pho_path", b2 =>
                                {
                                    b2.Property<int>("FilterPictureFoodId");

                                    b2.Property<int>("FilterPictureid");

                                    b2.Property<string>("LocalizedUrl");

                                    b2.Property<string>("OriginalUrl");

                                    b2.HasKey("FilterPictureFoodId", "FilterPictureid");

                                    b2.ToTable("SDTAFoodDetailFilterPictures");

                                    b2.HasOne("TourInfo.Domain.DomainModel.SDTA.FoodDetail+Data+FilterPicture")
                                        .WithOne("pho_path")
                                        .HasForeignKey("TourInfo.Domain.Base.ImageUrl", "FilterPictureFoodId", "FilterPictureid")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });
                        });

                    b.OwnsMany("TourInfo.Domain.DomainModel.SDTA.FoodDetail+Data+Picture", "pictures", b1 =>
                        {
                            b1.Property<int>("FoodId");

                            b1.Property<int>("id");

                            b1.Property<string>("created_at");

                            b1.Property<string>("deleted_at");

                            b1.Property<int>("is_404");

                            b1.Property<string>("pho_format");

                            b1.Property<string>("pho_id");

                            b1.Property<string>("pho_name");

                            b1.Property<string>("pho_type");

                            b1.Property<string>("picable_id");

                            b1.Property<string>("picable_type");

                            b1.Property<int>("rank");

                            b1.Property<string>("updated_at");

                            b1.HasKey("FoodId", "id");

                            b1.ToTable("SDTAFoodDetailPictures");

                            b1.HasOne("TourInfo.Domain.DomainModel.SDTA.FoodDetail+Data")
                                .WithMany("pictures")
                                .HasForeignKey("FoodId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsOne("TourInfo.Domain.Base.ImageUrl", "pho_path", b2 =>
                                {
                                    b2.Property<int>("PictureFoodId");

                                    b2.Property<int>("Pictureid");

                                    b2.Property<string>("LocalizedUrl");

                                    b2.Property<string>("OriginalUrl");

                                    b2.HasKey("PictureFoodId", "Pictureid");

                                    b2.ToTable("SDTAFoodDetailPictures");

                                    b2.HasOne("TourInfo.Domain.DomainModel.SDTA.FoodDetail+Data+Picture")
                                        .WithOne("pho_path")
                                        .HasForeignKey("TourInfo.Domain.Base.ImageUrl", "PictureFoodId", "Pictureid")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });
                        });

                    b.OwnsOne("TourInfo.Domain.DomainModel.SDTA.FoodDetail+Data+SnackFoodType", "snack_food_type", b1 =>
                        {
                            b1.Property<int>("id");

                            b1.Property<string>("created_at");

                            b1.Property<string>("deleted_at");

                            b1.Property<string>("food_type_id");

                            b1.Property<string>("food_type_id_p");

                            b1.Property<string>("food_type_name");

                            b1.Property<string>("grade");

                            b1.Property<string>("updated_at");

                            b1.Property<string>("user_id");

                            b1.HasKey("id");

                            b1.ToTable("SDTAFoodDetail");

                            b1.HasOne("TourInfo.Domain.DomainModel.SDTA.FoodDetail+Data")
                                .WithOne("snack_food_type")
                                .HasForeignKey("TourInfo.Domain.DomainModel.SDTA.FoodDetail+Data+SnackFoodType", "id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TourInfo.Domain.Base.ImageUrl", "defaultphoto", b1 =>
                        {
                            b1.Property<int>("Dataid");

                            b1.Property<string>("LocalizedUrl");

                            b1.Property<string>("OriginalUrl");

                            b1.HasKey("Dataid");

                            b1.ToTable("SDTAFoodDetail");

                            b1.HasOne("TourInfo.Domain.DomainModel.SDTA.FoodDetail+Data")
                                .WithOne("defaultphoto")
                                .HasForeignKey("TourInfo.Domain.Base.ImageUrl", "Dataid")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.SDTA.LineDetail", b =>
                {
                    b.OwnsMany("TourInfo.Domain.DomainModel.SDTA.LineDetail+Day", "days", b1 =>
                        {
                            b1.Property<string>("LineId");

                            b1.Property<string>("name");

                            b1.Property<string>("desc");

                            b1.Property<string>("foodDesc");

                            b1.Property<string>("hotelDesc");

                            b1.HasKey("LineId", "name");

                            b1.ToTable("SDTALineDetailDay");

                            b1.HasOne("TourInfo.Domain.DomainModel.SDTA.LineDetail")
                                .WithMany("days")
                                .HasForeignKey("LineId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsMany("TourInfo.Domain.DomainModel.SDTA.LineDetail+Day+Place", "place", b2 =>
                                {
                                    b2.Property<string>("LineId");

                                    b2.Property<string>("name");

                                    b2.Property<string>("id");

                                    b2.Property<string>("tag");

                                    b2.Property<string>("time");

                                    b2.Property<string>("type");

                                    b2.HasKey("LineId", "name", "id");

                                    b2.ToTable("SDTALineDetailDayPlace");

                                    b2.HasOne("TourInfo.Domain.DomainModel.SDTA.LineDetail+Day")
                                        .WithMany("place")
                                        .HasForeignKey("LineId", "name")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });
                        });

                    b.OwnsOne("TourInfo.Domain.Base.ImageUrl", "thumb", b1 =>
                        {
                            b1.Property<string>("LineDetailid");

                            b1.Property<string>("LocalizedUrl");

                            b1.Property<string>("OriginalUrl");

                            b1.HasKey("LineDetailid");

                            b1.ToTable("SDTALineDetail");

                            b1.HasOne("TourInfo.Domain.DomainModel.SDTA.LineDetail")
                                .WithOne("thumb")
                                .HasForeignKey("TourInfo.Domain.Base.ImageUrl", "LineDetailid")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.SDTA.LineDetailScenic+Doc+Source", b =>
                {
                    b.OwnsMany("TourInfo.Domain.DomainModel.SDTA.LineDetailScenic+Doc+Source+Eletype", "eletype", b1 =>
                        {
                            b1.Property<string>("sourceid");

                            b1.Property<string>("id");

                            b1.Property<string>("ancestors");

                            b1.Property<int>("level");

                            b1.Property<string>("value");

                            b1.HasKey("sourceid", "id");

                            b1.ToTable("SDTALineDetailScenicDocSourceEletype");

                            b1.HasOne("TourInfo.Domain.DomainModel.SDTA.LineDetailScenic+Doc+Source")
                                .WithMany("eletype")
                                .HasForeignKey("sourceid")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TourInfo.Domain.Base.ImageUrl", "default_photo", b1 =>
                        {
                            b1.Property<string>("Sourceid");

                            b1.Property<string>("LocalizedUrl");

                            b1.Property<string>("OriginalUrl");

                            b1.HasKey("Sourceid");

                            b1.ToTable("SDTALineDetailScenicDocSource");

                            b1.HasOne("TourInfo.Domain.DomainModel.SDTA.LineDetailScenic+Doc+Source")
                                .WithOne("default_photo")
                                .HasForeignKey("TourInfo.Domain.Base.ImageUrl", "Sourceid")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.SDTA.SpecialLocalProductDetail+Data", b =>
                {
                    b.HasOne("TourInfo.Domain.DomainModel.SDTA.SpecialLocalProductDetail+Data+CommodityType", "commodity_type")
                        .WithMany()
                        .HasForeignKey("commodity_typeid");

                    b.OwnsMany("TourInfo.Domain.DomainModel.SDTA.SpecialLocalProductDetail+Data+CommodityPrice", "commodity_prices", b1 =>
                        {
                            b1.Property<int>("SpecialLocalProducId");

                            b1.Property<string>("comm_price_id");

                            b1.Property<string>("commodity_id");

                            b1.Property<string>("created_at");

                            b1.Property<string>("goods_caption");

                            b1.Property<int>("price_caption");

                            b1.Property<int>("price_type");

                            b1.Property<string>("updated_at");

                            b1.HasKey("SpecialLocalProducId", "comm_price_id");

                            b1.ToTable("CommodityPrice");

                            b1.HasOne("TourInfo.Domain.DomainModel.SDTA.SpecialLocalProductDetail+Data")
                                .WithMany("commodity_prices")
                                .HasForeignKey("SpecialLocalProducId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TourInfo.Domain.DomainModel.SDTA.SpecialLocalProductDetail+Data+Destination", "destination", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("adm_address");

                            b1.Property<string>("adm_name");

                            b1.Property<string>("adm_phone");

                            b1.Property<string>("airlines");

                            b1.Property<string>("area_id");

                            b1.Property<int>("audit_state");

                            b1.Property<string>("bus");

                            b1.Property<string>("charmcitypic");

                            b1.Property<string>("cityname");

                            b1.Property<string>("clim_des");

                            b1.Property<string>("created_at");

                            b1.Property<string>("culture");

                            b1.Property<string>("daren_picture");

                            b1.Property<string>("dest_adver");

                            b1.Property<string>("dest_des");

                            b1.Property<int>("dest_type_id");

                            b1.Property<string>("destination_id");

                            b1.Property<string>("destname");

                            b1.Property<string>("fea_inf");

                            b1.Property<string>("fea_traffic");

                            b1.Property<string>("full_name");

                            b1.Property<string>("highway");

                            b1.Property<int>("is_404");

                            b1.Property<string>("keywords");

                            b1.Property<string>("latitude");

                            b1.Property<string>("longitude");

                            b1.Property<string>("notes_des");

                            b1.Property<string>("railway");

                            b1.Property<int>("rank");

                            b1.Property<string>("short_name");

                            b1.Property<string>("tags");

                            b1.Property<string>("taxi");

                            b1.Property<string>("tou_taboo");

                            b1.Property<string>("updated_at");

                            b1.Property<string>("water_carriage");

                            b1.Property<string>("website");

                            b1.HasKey("id");

                            b1.ToTable("SDTASpecialLocalProductDetail");

                            b1.HasOne("TourInfo.Domain.DomainModel.SDTA.SpecialLocalProductDetail+Data")
                                .WithOne("destination")
                                .HasForeignKey("TourInfo.Domain.DomainModel.SDTA.SpecialLocalProductDetail+Data+Destination", "id")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsOne("TourInfo.Domain.Base.ImageUrl", "defaultphoto", b2 =>
                                {
                                    b2.Property<int>("Destinationid")
                                        .ValueGeneratedOnAdd()
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<string>("LocalizedUrl");

                                    b2.Property<string>("OriginalUrl");

                                    b2.HasKey("Destinationid");

                                    b2.ToTable("SDTASpecialLocalProductDetail");

                                    b2.HasOne("TourInfo.Domain.DomainModel.SDTA.SpecialLocalProductDetail+Data+Destination")
                                        .WithOne("defaultphoto")
                                        .HasForeignKey("TourInfo.Domain.Base.ImageUrl", "Destinationid")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });
                        });

                    b.OwnsMany("TourInfo.Domain.DomainModel.SDTA.SpecialLocalProductDetail+Data+FilterPicture", "filter_pictures", b1 =>
                        {
                            b1.Property<int>("SpecialLocalProducId");

                            b1.Property<int>("id");

                            b1.Property<string>("created_at");

                            b1.Property<string>("deleted_at");

                            b1.Property<int>("is_404");

                            b1.Property<string>("pho_format");

                            b1.Property<string>("pho_id");

                            b1.Property<string>("pho_name");

                            b1.Property<string>("pho_type");

                            b1.Property<string>("picable_id");

                            b1.Property<string>("picable_type");

                            b1.Property<int>("rank");

                            b1.Property<string>("updated_at");

                            b1.HasKey("SpecialLocalProducId", "id");

                            b1.ToTable("SDTASpecialLocalProductDetailFilterPictures");

                            b1.HasOne("TourInfo.Domain.DomainModel.SDTA.SpecialLocalProductDetail+Data")
                                .WithMany("filter_pictures")
                                .HasForeignKey("SpecialLocalProducId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsOne("TourInfo.Domain.Base.ImageUrl", "pho_path", b2 =>
                                {
                                    b2.Property<int>("FilterPictureSpecialLocalProducId");

                                    b2.Property<int>("FilterPictureid");

                                    b2.Property<string>("LocalizedUrl");

                                    b2.Property<string>("OriginalUrl");

                                    b2.HasKey("FilterPictureSpecialLocalProducId", "FilterPictureid");

                                    b2.ToTable("SDTASpecialLocalProductDetailFilterPictures");

                                    b2.HasOne("TourInfo.Domain.DomainModel.SDTA.SpecialLocalProductDetail+Data+FilterPicture")
                                        .WithOne("pho_path")
                                        .HasForeignKey("TourInfo.Domain.Base.ImageUrl", "FilterPictureSpecialLocalProducId", "FilterPictureid")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });
                        });

                    b.OwnsMany("TourInfo.Domain.DomainModel.SDTA.SpecialLocalProductDetail+Data+Picture", "pictures", b1 =>
                        {
                            b1.Property<int>("SpecialLocalProducId");

                            b1.Property<int>("id");

                            b1.Property<string>("created_at");

                            b1.Property<string>("deleted_at");

                            b1.Property<int>("is_404");

                            b1.Property<string>("pho_format");

                            b1.Property<string>("pho_id");

                            b1.Property<string>("pho_name");

                            b1.Property<string>("pho_type");

                            b1.Property<string>("picable_id");

                            b1.Property<string>("picable_type");

                            b1.Property<int>("rank");

                            b1.Property<string>("updated_at");

                            b1.HasKey("SpecialLocalProducId", "id");

                            b1.ToTable("SDTASpecialLocalProductDetailPictures");

                            b1.HasOne("TourInfo.Domain.DomainModel.SDTA.SpecialLocalProductDetail+Data")
                                .WithMany("pictures")
                                .HasForeignKey("SpecialLocalProducId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsOne("TourInfo.Domain.Base.ImageUrl", "pho_path", b2 =>
                                {
                                    b2.Property<int>("PictureSpecialLocalProducId");

                                    b2.Property<int>("Pictureid");

                                    b2.Property<string>("LocalizedUrl");

                                    b2.Property<string>("OriginalUrl");

                                    b2.HasKey("PictureSpecialLocalProducId", "Pictureid");

                                    b2.ToTable("SDTASpecialLocalProductDetailPictures");

                                    b2.HasOne("TourInfo.Domain.DomainModel.SDTA.SpecialLocalProductDetail+Data+Picture")
                                        .WithOne("pho_path")
                                        .HasForeignKey("TourInfo.Domain.Base.ImageUrl", "PictureSpecialLocalProducId", "Pictureid")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });
                        });

                    b.OwnsOne("TourInfo.Domain.Base.ImageUrl", "defaultphoto", b1 =>
                        {
                            b1.Property<int>("Dataid")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("LocalizedUrl");

                            b1.Property<string>("OriginalUrl");

                            b1.HasKey("Dataid");

                            b1.ToTable("SDTASpecialLocalProductDetail");

                            b1.HasOne("TourInfo.Domain.DomainModel.SDTA.SpecialLocalProductDetail+Data")
                                .WithOne("defaultphoto")
                                .HasForeignKey("TourInfo.Domain.Base.ImageUrl", "Dataid")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TourInfo.Domain.DomainModel.WHY.WhyModel", b =>
                {
                    b.OwnsOne("TourInfo.Domain.Base.ImageUrl", "hposter", b1 =>
                        {
                            b1.Property<string>("WhyModelid");

                            b1.Property<string>("LocalizedUrl");

                            b1.Property<string>("OriginalUrl");

                            b1.HasKey("WhyModelid");

                            b1.ToTable("WHYDetailOrganizations");

                            b1.HasOne("TourInfo.Domain.DomainModel.WHY.WhyModel")
                                .WithOne("hposter")
                                .HasForeignKey("TourInfo.Domain.Base.ImageUrl", "WhyModelid")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TourInfo.Domain.Base.Location", "location", b1 =>
                        {
                            b1.Property<string>("WhyModelid");

                            b1.Property<double>("Latitude");

                            b1.Property<double>("Longitude");

                            b1.HasKey("WhyModelid");

                            b1.ToTable("WHYDetailOrganizations");

                            b1.HasOne("TourInfo.Domain.DomainModel.WHY.WhyModel")
                                .WithOne("location")
                                .HasForeignKey("TourInfo.Domain.Base.Location", "WhyModelid")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TourInfo.Domain.ZBTA.ZbtaNews", b =>
                {
                    b.OwnsOne("TourInfo.Domain.Base.ImageUrlsInText", "details", b1 =>
                        {
                            b1.Property<string>("ZbtaNewsid");

                            b1.Property<string>("ImageBaseUrl");

                            b1.Property<string>("ImageLocalizedText");

                            b1.Property<string>("OriginaText");

                            b1.HasKey("ZbtaNewsid");

                            b1.ToTable("ZbtaNews");

                            b1.HasOne("TourInfo.Domain.ZBTA.ZbtaNews")
                                .WithOne("details")
                                .HasForeignKey("TourInfo.Domain.Base.ImageUrlsInText", "ZbtaNewsid")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TourInfo.Domain.Base.ImageUrl", "image", b1 =>
                        {
                            b1.Property<string>("ZbtaNewsid");

                            b1.Property<string>("LocalizedUrl");

                            b1.Property<string>("OriginalUrl");

                            b1.HasKey("ZbtaNewsid");

                            b1.ToTable("ZbtaNews");

                            b1.HasOne("TourInfo.Domain.ZBTA.ZbtaNews")
                                .WithOne("image")
                                .HasForeignKey("TourInfo.Domain.Base.ImageUrl", "ZbtaNewsid")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TourInfo.Domain.EWQYEntity", b =>
                {
                    b.OwnsMany("TourInfo.Domain.Base.ImageUrl", "pictureKeys", b1 =>
                        {
                            b1.Property<string>("OriginalUrl");

                            b1.Property<string>("id");

                            b1.Property<string>("LocalizedUrl");

                            b1.HasKey("OriginalUrl", "id");

                            b1.HasIndex("id");

                            b1.ToTable("EWQYPlaceTypeEntities_pictureKeys");

                            b1.HasOne("TourInfo.Domain.EWQYEntity")
                                .WithMany("pictureKeys")
                                .HasForeignKey("id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TourInfo.Domain.Base.ImageUrl", "thumbnailKey", b1 =>
                        {
                            b1.Property<string>("EWQYEntityid");

                            b1.Property<string>("LocalizedUrl");

                            b1.Property<string>("OriginalUrl");

                            b1.HasKey("EWQYEntityid");

                            b1.ToTable("EWQYPlaceTypeEntities");

                            b1.HasOne("TourInfo.Domain.EWQYEntity")
                                .WithOne("thumbnailKey")
                                .HasForeignKey("TourInfo.Domain.Base.ImageUrl", "EWQYEntityid")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TourInfo.Domain.CompanyVenue", b =>
                {
                    b.OwnsOne("TourInfo.Domain.Base.Location", "location", b1 =>
                        {
                            b1.Property<string>("CompanyVenueid");

                            b1.Property<double>("Latitude");

                            b1.Property<double>("Longitude");

                            b1.HasKey("CompanyVenueid");

                            b1.ToTable("CompanyVanueLocations");

                            b1.HasOne("TourInfo.Domain.CompanyVenue")
                                .WithOne("location")
                                .HasForeignKey("TourInfo.Domain.Base.Location", "CompanyVenueid")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
